export const CONFIG = {
  shopName: "The Deviant's Shelf",
  tagline: "A small apothecary for people who already know where to look.",
  // Change these before you send the link to anyone.
  memberPin: "8008",
  adminPin: "8335",
  receiptHours: 24,
  pay: {
    note: "No payment is taken in the app. Send the exact order total, then attach the receipt on Active Orders.",
    ownerName: "Brandon Melton",
    venmo: "@B-Melt",
    zelle: "SET ZELLE",
    cashApp: "$Slycinder",
    chime: "$Brandon-Melton-44",
    crypto: "USDT (TRC-20) or BTC — ask for the wallet on the order.",
  },
  shipping: [
    { id: "usps", label: "USPS", detail: "3–5 days", price: 12 },
    { id: "fedex2", label: "FedEx 2 Day", detail: "2 Day Air", price: 20 },
    { id: "overnight", label: "FedEx Overnight", detail: "Overnight", price: 60 },
  ],
};

export const PRODUCTS = [
  {
    id: "r3",
    code: "R3",
    name: "Retatrutide",
    blurb: "Triple agonist research analog.",
    sizes: [
      { sku: "R3-5", mg: "5 mg", vial: 45 },
      { sku: "R3-20", mg: "20 mg", vial: 100 },
    ],
  },
  {
    id: "amq",
    code: "AMQ",
    name: "5-Amino-1MQ",
    blurb: "NNMT research compound.",
    sizes: [{ sku: "AMQ-50", mg: "50 mg", vial: 65 }],
  },
  {
    id: "bpc",
    code: "BPC",
    name: "BPC-157",
    blurb: "Pentadecapeptide research standard.",
    sizes: [
      { sku: "BPC-5", mg: "5 mg", vial: 25 },
      { sku: "BPC-10", mg: "10 mg", vial: 40 },
    ],
  },
  {
    id: "tb5",
    code: "TB5",
    name: "TB-500",
    blurb: "Thymosin β4 fragment.",
    sizes: [{ sku: "TB5-5", mg: "5 mg", vial: 55 }],
  },
  {
    id: "mot",
    code: "MOT",
    name: "MOTS-c",
    blurb: "Mitochondrial-derived peptide.",
    sizes: [{ sku: "MOT-20", mg: "20 mg", vial: 50 }],
  },
  {
    id: "kpv",
    code: "KPV",
    name: "KPV",
    blurb: "α-MSH fragment.",
    sizes: [{ sku: "KPV-10", mg: "10 mg", vial: 35 }],
  },
  {
    id: "ara",
    code: "ARA",
    name: "ARA-290",
    blurb: "Cibinetide analog.",
    sizes: [{ sku: "ARA-10", mg: "10 mg", vial: 55 }],
  },
  {
    id: "cjc",
    code: "CJC",
    name: "CJC-1295 + Ipamorelin",
    blurb: "GHRH fragment + ghrelin analog.",
    sizes: [{ sku: "CJC-5-5", mg: "5 mg + 5 mg", vial: 70 }],
  },
  {
    id: "pin",
    code: "PIN",
    name: "Pinealon",
    blurb: "Tripeptide bioregulator.",
    sizes: [{ sku: "PIN-10", mg: "10 mg", vial: 45 }],
  },
  {
    id: "epi",
    code: "EPI",
    name: "Epithalon",
    blurb: "Pineal tetrapeptide.",
    sizes: [{ sku: "EPI-10", mg: "10 mg", vial: 20 }],
  },
  {
    id: "sel",
    code: "SEL",
    name: "Selank",
    blurb: "Tuftsin analog.",
    sizes: [{ sku: "SEL-5", mg: "5 mg", vial: 30 }],
  },
  {
    id: "sem",
    code: "SEM",
    name: "Semax",
    blurb: "ACTH fragment analog.",
    sizes: [{ sku: "SEM-10", mg: "10 mg", vial: 45 }],
  },
  {
    id: "nad",
    code: "NAD",
    name: "NAD+",
    blurb: "Nicotinamide adenine dinucleotide.",
    sizes: [
      { sku: "NAD-100", mg: "100 mg", vial: 30 },
      { sku: "NAD-500", mg: "500 mg", vial: 50 },
    ],
  },
  {
    id: "pt",
    code: "PT",
    name: "PT-141",
    blurb: "Bremelanotide analog.",
    sizes: [{ sku: "PT-10", mg: "10 mg", vial: 35 }],
  },
  {
    id: "ghk",
    code: "GHK",
    name: "GHK-Cu",
    blurb: "Copper tripeptide.",
    sizes: [{ sku: "GHK-100", mg: "100 mg", vial: 25 }],
  },
  {
    id: "bac",
    code: "BAC",
    name: "Bacteriostatic water",
    blurb: "Null Spring — reconstitution water.",
    sizes: [{ sku: "BAC-10", mg: "10 ml", vial: 10 }],
  },
  {
    id: "kit",
    code: "KIT",
    name: "Beginner alchemy kit",
    blurb: "Bac water · 10 syringes · 20 wipes.",
    sizes: [{ sku: "KIT-1", mg: "kit", vial: 20 }],
  },
];
